CREATE TABLE hk_chains (
    chain_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    chain_name VARCHAR2(100) NOT NULL,
    address VARCHAR2(200) NOT NULL,
    phone VARCHAR2(20),
    description CLOB,
    image_path VARCHAR2(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM hk_chains;

-- 1. 가맹점 테스트 데이터 추가
INSERT INTO hk_chains (chain_name, address, phone, description, image_path) 
VALUES ('헬킹 강남점', '서울시 강남구 테헤란로 123', '02-1234-5678', '강남 최대 규모의 헬스장입니다. 최신 운동기구와 전문 트레이너가 상주하고 있습니다.', 'gym1.jpg');

INSERT INTO hk_chains (chain_name, address, phone, description, image_path) 
VALUES ('헬킹 홍대점', '서울시 마포구 홍익로 456', '02-2345-6789', '젊은 분위기의 트렌디한 피트니스 센터입니다. 다양한 그룹 수업을 제공합니다.', 'gym2.jpg');

INSERT INTO hk_chains (chain_name, address, phone, description, image_path) 
VALUES ('헬킹 잠실점', '서울시 송파구 잠실동 789', '02-3456-7890', '넓은 공간과 수영장을 갖춘 종합 스포츠 센터입니다.', 'gym3.jpg');

INSERT INTO hk_chains (chain_name, address, phone, description, image_path) 
VALUES ('헬킹 부산점', '부산시 해운대구 해운대로 321', '051-1111-2222', '바다뷰를 감상하며 운동할 수 있는 특별한 공간입니다.', 'gym4.jpg');

INSERT INTO hk_chains (chain_name, address, phone, description, image_path) 
VALUES ('헬킹 대구점', '대구시 수성구 범어동 654', '053-3333-4444', '대구 지역 최고의 시설을 자랑하는 프리미엄 헬스장입니다.', 'gym5.jpg');

CREATE TABLE hk_chain_codes (
    chain_num NUMBER PRIMARY KEY,
    chain_code VARCHAR2(4) NOT NULL UNIQUE,
    is_active CHAR(1) DEFAULT 'Y',
    FOREIGN KEY (chain_num) REFERENCES hk_chains(chain_num)
);

-- 2. 체인 코드 데이터 추가 (chain_num은 실제 생성된 값으로 조정 필요)
INSERT INTO hk_chain_codes (chain_num, chain_code, is_active) VALUES (1, 'GN01', 'Y');
INSERT INTO hk_chain_codes (chain_num, chain_code, is_active) VALUES (2, 'HD01', 'Y');
INSERT INTO hk_chain_codes (chain_num, chain_code, is_active) VALUES (3, 'JS01', 'Y');
INSERT INTO hk_chain_codes (chain_num, chain_code, is_active) VALUES (4, 'BS01', 'Y');
INSERT INTO hk_chain_codes (chain_num, chain_code, is_active) VALUES (5, 'DG01', 'Y');

SELECT * FROM hk_chain_codes;

SELECT * FROM hk_chains WHERE ROWNUM <= 3;