-- ?��?��?��바디 ?��로그?�� ?��?���?
CREATE TABLE hk_design_body_programs (
    program_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    program_name VARCHAR2(100) NOT NULL,
    program_type VARCHAR2(20) NOT NULL, -- 'DIET', 'MUSCLE', 'CARDIO', 'REHAB'
    difficulty VARCHAR2(20) NOT NULL,    -- 'BEGINNER', 'INTERMEDIATE', 'ADVANCED'
    duration NUMBER NOT NULL,            -- ?��로그?�� 기간 (?��)
    description CLOB NOT NULL,
    instructor VARCHAR2(50) NOT NULL,
    image_path VARCHAR2(200),
    price NUMBER DEFAULT 0,
    target_audience VARCHAR2(500),       -- ???��?��
    equipment VARCHAR2(500),             -- ?��?�� ?���?
    schedule CLOB,                       -- ?���?�? ?���?
    is_active CHAR(1) DEFAULT 'Y',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ?��?��?��바디 ?��로그?�� ?���? ?��?���?
CREATE TABLE hk_design_body_enrollments (
    enroll_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_num NUMBER NOT NULL,
    program_num NUMBER NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR2(20) DEFAULT 'ACTIVE', -- 'ACTIVE', 'COMPLETED', 'CANCELLED', 'PAUSED'
    payment_id VARCHAR2(100),
    enroll_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_num) REFERENCES hk_users(user_num),
    FOREIGN KEY (program_num) REFERENCES hk_design_body_programs(program_num)
);

-- 초기 ?��로그?�� ?��?��?��
INSERT INTO hk_design_body_programs (program_name, program_type, difficulty, duration, description, instructor, price, target_audience, equipment, schedule) 
VALUES ('30?�� ?�� ?��?��?��?��', 'DIET', 'BEGINNER', 30, '집에?�� ?�� ?�� ?��?�� 기본?��?�� ?��?��?��?�� ?��로그?��?��?��?��.', '�??��?��?��?��', 49000, '?��?��?��?�� 초보?��, 집에?�� ?��?��?���? ?��?? �?', '?��?��매트', '�? 5?��, 1?�� 30�?');

INSERT INTO hk_design_body_programs (program_name, program_type, difficulty, duration, description, instructor, price, target_audience, equipment, schedule) 
VALUES ('근력강화 12�? ?��로그?��', 'MUSCLE', 'INTERMEDIATE', 84, '체계?��?�� 근력 ?��?��?�� ?��?�� 중급?�� ?��로그?��?��?��?��.', '박근?��', 89000, '근력 ?��?��?�� ?��?��?�� 중급?��', '?���?, 바벨', '�? 4?��, 1?�� 60�?');

INSERT INTO hk_design_body_programs (program_name, program_type, difficulty, duration, description, instructor, price, target_audience, equipment, schedule) 
VALUES ('?��?��?�� 마스?�� 6�?', 'CARDIO', 'BEGINNER', 42, '?��?���?구력 ?��?��?�� ?��?�� ?��로그?��?��?��?��.', '?��?��?��?��', 39000, '?��?��?�� ?��?�� ?��문자', '?��?��', '�? 3?��, 1?�� 45�?');

COMMIT WORK;

SELECT program_num, program_name, program_type, difficulty 
FROM hk_design_body_programs;

SELECT * FROM hk_design_body_programs WHERE program_type = 'DIET';