CREATE TABLE hk_qr_visits (
    visit_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_num NUMBER NOT NULL,
    chain_num NUMBER NOT NULL,
    visit_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    result VARCHAR2(20) NOT NULL,
    failure_reason VARCHAR2(200),
    FOREIGN KEY (user_num) REFERENCES hk_users(user_num),
    FOREIGN KEY (chain_num) REFERENCES hk_chains(chain_num)
);

-- 테스트용 방문 기록 추가
INSERT INTO hk_qr_visits (user_num, chain_num, result, visit_time) 
VALUES (4, 1, 'SUCCESS', SYSDATE - 1);

INSERT INTO hk_qr_visits (user_num, chain_num, result, visit_time) 
VALUES (4, 2, 'SUCCESS', SYSDATE - 2);

INSERT INTO hk_qr_visits (user_num, chain_num, result, failure_reason, visit_time) 
VALUES (4, 3, 'FAILED', '패스권 만료', SYSDATE - 3);

COMMIT WORK;