DROP TABLE validation_user PURGE;

CREATE TABLE hk_users (
    user_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id VARCHAR2(50) UNIQUE NOT NULL,
    username VARCHAR2(50) NOT NULL UNIQUE,
    email VARCHAR2(100) UNIQUE NOT NULL,
    phone VARCHAR2(20) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL, -- BCrypt 암호화
    profile_image VARCHAR2(200) DEFAULT 'avatar1.png',
    birth_date DATE,
    gender VARCHAR2(10),
    join_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR2(20) DEFAULT 'ACTIVE'
);

ALTER TABLE hk_users 
ADD CONSTRAINT uq_hk_users_username UNIQUE(username);

SELECT * FROM hk_users;

COMMIT

CREATE TABLE hk_user_auth (
    auth_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_num NUMBER NOT NULL,
    auth_type VARCHAR2(20) NOT NULL, -- 'SMS', 'EMAIL'
    auth_code VARCHAR2(6) NOT NULL,
    expire_time TIMESTAMP NOT NULL,
    is_verified CHAR(1) DEFAULT 'N',
    FOREIGN KEY (user_num) REFERENCES hk_users(user_num)
);

CREATE TABLE hk_social_users (
    social_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_num NUMBER NOT NULL,
    provider VARCHAR2(20) DEFAULT 'NAVER',
    social_user_id VARCHAR2(100) NOT NULL,
    FOREIGN KEY (user_num) REFERENCES hk_users(user_num)
);
